import { Noto_Sans_Thai } from "next/font/google";

import "bootstrap/dist/css/bootstrap.min.css"
import "./globals.css";
import BootstrapClient from "./components/BootstrapClient";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai", "latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSansThai.variable}`}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
